#!/bin/sh -e
sed -i -e '/AC_PATH_XTRA/d' configure.in
autoreconf --force --install

./configure --prefix=/usr --localstatedir=/var --sysconfdir=/etc
sed -i -e 's/ -shared / -WI, -O1, -as-needed\0/g' libtool
make

make DESTDIR="$1" install
